language: go
os:
  - osx
  - linux
go:
  - go1.13
go_import_path: github.com/novalagung/go-eek
before_install:
  - which go
  - rm -rf go.*
  - rm -rf vendor
  - go get github.com/mattn/goveralls
  - go get github.com/novalagung/gubrak
  - go get github.com/smartystreets/goconvey
script:
  - go test -cover -race -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci
